name: Zip magisk

on:
  push:
    branches:
      - magisk
    paths:
      - '*'
env:
  REPO_URL: https://github.com/Sirherobrine23/Moto-G7-Plus-sh23.git
  REPO_BRANCH: magisk
  UPLOAD_RELEASE: true
  TZ: America/Sao_Paulo

jobs:
  Magisk:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checando
      uses: actions/checkout@master

    - name: Inicializando
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install zip unzip dos2unix
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Clonando
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH zip-sh

    - name: Atualizando os Feeds
      run: |
       sudo mkdir files/
       cd zip-sh
       sudo dos2unix META-INF/com/google/android/update-binary
       sudo dos2unix *.sh
       sudo rm -rf README.md LICENSE *.git*
       sudo zip "$(TZ=UTC+3 date +"%d-%M-%Y-%H-%M-%S").zip" -r * 
       sudo mv *-*.zip ../files/
    
    - name: Gerando Tag
      id: tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")-TWRP-ZIP"
        echo "Zip Actions" >> release.txt
        echo "Twrp for Moto g7 Plus lake" >> release.txt
        echo "©Sirherobrine23" >> release.txt
        echo "::set-output name=status::success"
    
    - name: Upload do zip para o Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        body_path: release.txt
        files: files/*
