name: tag
on:
  push:
jobs:
  Tag-TWRP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.TOKEN }}
          release_branches: TWRP