name: tag
on:
  push:
jobs:
  Tag-TWRP:
    runs-on: ubuntu-latest
    steps:
      - name: Tag date
        run: |
          echo ::set-env name=DATAA::"$(TZ=UTC+3 date +"%H-%M-%S-%d/%m/%Y")-TWRP-Tag"
      - uses: actions/checkout@master
      - name: Tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.TOKEN }}
          release_branches: TWRP
          tag_prefix: ${{ env.DATAA }}