name: Zip TWRP

on:
  push:
env:
  REPO_URL: https://github.com/Sirherobrine23/Moto-G7-Plus-sh23.git
  REPO_BRANCH: TWRP
  UPLOAD_RELEASE: true
  EVENTO: "${{ github.event }}"
  TZ: America/Sao_Paulo

jobs:
  TWRP:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checando
      uses: actions/checkout@master

    - name: Inicializando
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install zip unzip dos2unix
        sudo timedatectl set-timezone "$TZ"

    - name: Clonando
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH zip-sh

    - name: Criando o Arquivo
      run: |
       sudo mkdir files/
       cd zip-sh
       sudo dos2unix META-INF/com/google/android/update-binary
       sudo rm -rf README.md LICENSE *.git*
       sudo zip "$(TZ=UTC+3 date +"%d-%m-%Y-%H-%M-%S").zip" -r * 
       sudo mv *-*.zip ../files/
    
    - name: Gerando o body
      id: tag
      run: |
        echo "©Sirherobrine23" >> release.txt
        echo "${{ env.EVENTO	}}" >> release.txt
        echo "${{ env.EVENTO	}}"
        echo "::set-output name=status::success"
    
    - name: Upload do zip para o Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: echo ::set-env name=RELEASE_TAG::""
        body_path: release.txt
        files: files/*